language: python
python: "2.7"
sudo: false
cache: pip
install:
  - pip install ansible
script:
  - ansible-galaxy install --force -r galaxy-roles.txt -p roles/
  - ansible-playbook --syntax-check -i hosts/development site.yml