---
- name: "WordPress Server: Install LEMP Stack with PHP 5.6 and MariaDB MySQL"
  hosts: web
  sudo: yes
  remote_user: root

  roles:
    - { role: common, tags: [common] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: mariadb, tags: [mariadb] }
    - { role: ssmtp, tags: [ssmtp mail] }
    - { role: php, tags: [php] }
    - { role: nginx, tags: [nginx] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: deploy, tags: [deploy] }
    - { role: bfmartin.ssh_known_hosts, host: github.com, dest: "/home/{{ deploy_user }}/.ssh/known_hosts" }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup] }